### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by enricobono**
The `global.json` config file currently contains only translations for english, french and german.
I'd like to contribute with the italian translation.

### CODE REVIEW

**Comment by onigoetz** [comment]
This is so cool, thanks.

However, I added seven new strings to translate last week, can you translate them as well please ? 

```
   "Search_one_result": "1 result",
   "Search_results": "!count results",
   "Search_no_results": "Nothing found",
   "Search_common_words_ignored": "Common words are largely ignored",
   "Search_too_short": "Search too short",
   "Search_one_character_or_more": "Should be one character or more",
   "Search_should_be_x_or_more": "Should be !min characters or more",
```

https://github.com/dauxio/daux.io/blob/master/global.json#L31-L37

Thanks in advance

**Comment by enricobono** [comment]
Sure :)

**Comment by enricobono** [comment]
I added the new strings.

**Comment by onigoetz** [comment]
Thanks :)

**Pull request merged**
