### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by aedart**
See #42

### CODE REVIEW

**Comment by aedart** [comment]
Not sure about the JavaScript dependencies. I haven't touched them for this pull request. Yet for the php, it appears that everything is fine. Please note, the assumption is that you drop support for php 5.x and 7.0 and go straight for php 7.1.x (**I highly recommend this!**)

**Comment by onigoetz** [comment]
Thanks for your pull request

I agree, for the support let's move to PHP 7.1

**Comment by aedart** [comment]
@onigoetz Once again, huge ty :)

**Comment by aedart** [comment]
Btw, while waiting for the updates, I applied the following work-around (some time last week).
I managed to install your package, using this composer plugin. It actually works really great.
Perhaps you should try it - and consider it as an "install alternative", in your documentation.

See composer plugin at https://github.com/bamarni/composer-bin-plugin

**Pull request merged**
